### ISSUE TITLE
-ftb-complete:11: command not found: -ftb-generate-complist

### ISSUE THREAD

**Issue by delucca** [Aloxaf/fzf-tab#134]
Hey!

I've just upgraded to the most recent version (after the major refactor) and now my `fzf-tab` is not working anymore.

I had this config previously:
```sh
export FZF_TAB_OPTS=(
   --expect='/'
   --color='hl:$(( $#headers == 0 ? 108 : 255 ))'
   --nth='2,3'
   --delimiter='\0'
   --tiebreak=begin -m --bind=tab:down,change:top,ctrl-space:toggle --cycle
   --query='$query'
   --header-lines='$#headers'
   --preview-window='0%'
 )
```

I've already deactivated my old configs, but when I tap `TAB` to test it I got the following error:

```sh
-ftb-complete:11: command not found: -ftb-generate-complist
```

And then the standard zsh-autocomplete appears.

Here is a copy of my `.zshrc`:

```
#!/usr/bin/env zsh

##
# ---- Configure tools ----
##

current_emulator=$(pstree -sA $$)

# Bash Hub
source ~/.bashhub/bashhub.zsh

# Enhancd
source ~/.enhancd/bin/init.sh

# asdf
source /opt/asdf-vm/asdf.sh

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5E5E5E"

# Desk
[ -n "$DESK_ENV" ] && source "$DESK_ENV" || desk go shared.common

# Keychain
zstyle :omz:plugins:keychain agents gpg,ssh
zstyle :omz:plugins:keychain identities id_rsa

# compinit
autoload -U compinit

##
# ---- Load Zplugin ----
##
source ${HOME}/.zinit/bin/zinit.zsh

##
# ---- Load plugins ---

# Order sensitive plugins
zinit light "Aloxaf/fzf-tab"

# Oh-my-zsh configs that I want
zinit snippet "OMZ::lib/completion.zsh"
zinit snippet "OMZ::lib/history.zsh"
zinit snippet "OMZ::lib/key-bindings.zsh"
zinit snippet "OMZ::lib/theme-and-appearance.zsh"
zinit snippet "OMZ::lib/spectrum.zsh"
zinit snippet "OMZ::plugins/git/git.plugin.zsh"
zinit snippet "OMZ::plugins/git-extras/git-extras.plugin.zsh"
zinit snippet "OMZ::plugins/kubectl/kubectl.plugin.zsh"
zinit snippet "OMZ::plugins/fzf/fzf.plugin.zsh"
zinit snippet "OMZ::plugins/dotenv/dotenv.plugin.zsh"
zinit snippet "OMZ::plugins/keychain/keychain.plugin.zsh"

# Improving ZSH usage
zinit light "denysdovhan/spaceship-prompt"
zinit light "chrissicool/zsh-256color"
zinit light "rupa/z"
zinit light "changyuheng/fz"
zinit light "djui/alias-tips"
zinit light "supercrabtree/k"
zinit light "zsh-users/zsh-autosuggestions"
zinit light "zsh-users/zsh-syntax-highlighting"
zinit light "zsh-users/zsh-history-substring-search"
zinit light "Tarrasch/zsh-bd"
zinit light "changyuheng/zsh-interactive-cd"
zinit light "shannonmoeller/up"
zinit light "tcnksm/docker-alias"
zinit light "bonnefoa/kubectl-fzf"
zinit light "jamesob/desk"
zinit light "relastle/pmy"
zinit light "b4b4r07/emoji-cli"

zinit cdreplay -q

# Autoload tmux
if [ -z "$TMUX" ] && [[ $current_emulator == *"termite"* ]]; then
  tmuxinator start default
fi
```

Can anyone help? Thanks :)

**EDIT 1:**

If I deactivate everything from my configs (let only the `fzf-tab` I got the following error when I press tab:

```sh
odelucca-pc% git _ftb__main_complete:45: command not found: _setup
odelucca-pc% git _ftb__main_complete:96: permission denied: 
_ftb__main_complete:135: command not found: _complete
_ftb__main_complete:135: command not found: _ignored
_ftb__main_complete:322: permission denied: 

## FOR REFERENCE, this test .zshrc was
source ${HOME}/.zinit/bin/zinit.zsh

autoload -U compinit

zinit light "Aloxaf/fzf-tab"
zinit snippet "OMZ::plugins/fzf/fzf.plugin.zsh"
```

**Comment by Aloxaf** [comment]
What's your zsh version?

I guess this is because autoloading with an absolute path only works on the newer version of zsh.

**Comment by NICHOLAS85** [comment]
I use `$ZSH_VERSION=5.8` and run into the same issue with autoloading absolute paths not working. I think it is a Zinit bug as sourcing plugins manually which autoload using the absolute path works.

https://github.com/zdharma/zinit/issues/422#issue-719706408

**Comment by delucca** [comment]
@Aloxaf 5.8 here too:
``❯ zsh --version
zsh 5.8 (x86_64-pc-linux-gnu)
````

**Comment by Aloxaf** [comment]
This should be fixed in https://github.com/Aloxaf/fzf-tab/commit/a7c4890445d6c7a8cc7b64fed3c4e62711ad5b5f

**Comment by delucca** [comment]
Great. Now it is working as expected.

Just a quick question, the preview window now is displaying the following error (no matter the command I'm using):
```
fork/exec /usr/bin/zsh: invalid argument
```

There are any additional config I need to do?

**Comment by Aloxaf** [comment]
@delucca 
That's strange. What's your preview configuration?

**Comment by delucca** [comment]
@Aloxaf I tried the suggested config:
```
zstyle ':fzf-tab:complete:*:*' extra-opts --preview=$extract";$PREVIEW \$in"
```

But the issue persists. Here is my previous config:
```
export FZF_TAB_OPTS=(
  --expect='/'
  --color='hl:$(( $#headers == 0 ? 108 : 255 ))'
  --nth='2,3'
  --delimiter='\0'
  --tiebreak=begin -m --bind=tab:down,change:top,ctrl-space:toggle --cycle
  --query='$query'
  --header-lines='$#headers'
  --preview-window='0%'
)
```

But I've removed that config entirely. Now I've just installed `fzf-tab` as is

Also, I've some custom `fzf` configs (they still active):

```
export FZF_DEFAULT_OPTS="\
  --ansi \
  --cycle \
  --layout='reverse' \
  --height='20' \
  --preview='(highlight -O ansi -l {} 2> /dev/null || bat --style=numbers --color=always {} || cat {} || tree -L 2 -C {}) 2> /dev/null | head -200' \
  --preview-window='right:70%:noborder' \
  --bind='?:toggle-preview' \
  --bind='tab:down' \
"
export FZF_DEFAULT_COMMAND_OPTS="
  --hidden \
  --follow \
  --type='f' \
  --exclude='.git' \
"
export FZF_CTRL_R_OPTS="
  --sort \
  --exact \
  --preview-window='down:3:hidden:wrap' \
"
export FZF_CTRL_T_OPTS="
  --select-1 \
  --exit-0 \
"
export FZF_ALT_C_OPTS="
  --select-1 \
  --exit-0 \
"
export FZF_DEFAULT_COMMAND="fd ${FZF_DEFAULT_COMMAND_OPTS}"
```

**Comment by Aloxaf** [comment]
How about this:

``zsh
zstyle ':fzf-tab:complete:*' fzf-preview --preview='
echo word: $word
echo description: $desc
echo group: $group
if (( $+ctxt[isfile] )); then
  echo path: $realpath
fi
'
```

**Comment by delucca** [comment]
@Aloxaf sorry for the late reply.

I've added that config, and now the error ir:
```
zsh:10: bad math expression: empty string
```

**Comment by Aloxaf** [comment]
@delucca Oh, it's bug that I haven't noticed before! 

Please try this again:
```zsh
zstyle ':fzf-tab:complete:*' fzf-preview '
echo word: $word
echo description: $desc
(( $+ctxt[group] )) && echo group: $group
(( $+ctxt[isfile] )) && echo path: $realpath
'
```

**Comment by delucca** [comment]
@Aloxaf same error :/ (I'm testing with `cat`)

**Comment by Aloxaf** [comment]
@delucca have you updated to the latest master?

**Comment by delucca** [comment]
@Aloxaf ah cool, now it works. But, quick question, after typing `cat`, for example, it shows the following preview:

```
word: package.json
description: package.json
```

how can I see an actual preview of its contents?

**Comment by Aloxaf** [comment]
Just change it to any command you want:

```zsh
zstyle ':fzf-tab:complete:cat:argument-rest' fzf-preview '[[ $(file --mime-type $realpath) == *"text/"* ]] && cat $realpath'
```

**Comment by delucca** [comment]
Oh! great, thanks :D

**Comment by pnchinmay** [comment]
Hey @Aloxaf, thanks for such an awesome tool. Works like a charm.
Only error I was getting in case of previews.
I was able to get something similar to
```
word: package.json
description: package.json
```
But, after adding the below snippet, I'm getting error as `No such file or directory` in preview window


> Just change it to any command you want:
> 
> ```shell
> zstyle ':fzf-tab:complete:cat:argument-rest' fzf-preview '[[ $(file --mime-type $realpath) == *"text/"* ]] && cat $realpath'
> ```
Any clue you could drop or somewhere you could redirect to ?
Thanks
